routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('/', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login-form');;
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...

    // if (config('auth.users.registration')) {
        //Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    // }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    
    // Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    // Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    //Managers
    Route::get('users/manager/create', 'UserController@createManager')->name('users.create');
    Route::post('users/manager/store', 'UserController@storeManager')->name('users.manager.store');
    
    //Stations
    Route::get('stations', 'StationController@index')->name('stations');
    Route::post('stations', 'StationController@store')->name('stations.store');
    Route::get('stations/new', 'StationController@create')->name('stations.create');
    Route::get('stations/{station}', 'StationController@show')->name('stations.show');
    Route::get('stations/{station}/edit', 'StationController@edit')->name('stations.edit');
    Route::put('stations/{station}', 'StationController@update')->name('stations.update');

    //Panels
    Route::get('panels', 'PanelController@index')->name('panels');
    Route::post('panels', 'PanelController@store')->name('panels.store');
    Route::get('panels/new', 'PanelController@create')->name('panels.create');
    Route::get('panels/{panel}', 'PanelController@show')->name('panels.show');
    Route::get('panels/{panel}/edit', 'PanelController@edit')->name('panels.edit');
    Route::put('panels/{panel}', 'PanelController@update')->name('panels.update');

    //Operations
    Route::get('operations', 'OperationController@index')->name('operations');
    Route::post('operations', 'OperationController@index')->name('operations.filter');
    Route::get('operations/bystation/{id}', 'OperationController@filterByStation')->name('operations.filter.bystation');
    Route::post('operations/bystation/{id}', 'OperationController@filterByStation')->name('operations.filter.bystation');
    // Route::get('operations/bystation', 'OperationController@filterByStation')->name('operations.filter.bys');
    Route::get('operations/{operation}', 'OperationController@show')->name('operations.show');
    // Route::post('operations/filter/by-station', 'OperationController@filter')->name('operations.filter');
    
    // Route::post('operations', 'OperationController@store')->name('operations.store');
    // Route::get('operations/new', 'OperationController@create')->name('operations.create');
    // Route::get('operations/{operation}/edit', 'OperationController@edit')->name('operations.edit');
    // Route::put('operations/{operation}', 'OperationController@update')->name('operations.update');
    
    //Permissions
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
    Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
    Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
});


// Route::get('/', 'HomeController@index');

/**
 * Membership
 */

// Route::group(['as' => 'protection.'], function () {
//     Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
//     Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
//     Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
// });

app/Station.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
    public $sortable = ['created_at'];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'stations';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['description', 'address', 'long','lat','manager','mobile','fax','fix'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Get the Panels for the Station.
     */
    public function panels()
    {
        return $this->hasMany('App\Panel');
    }

}

app/Http/Controllers/API/StationController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Auth\Role\Role;
use App\Station;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Http\Resources\StationResource;
use Flugg\Responder\Responder;
use App\Transformers\StationTransformer;

class StationController extends Controller
{
    public function index()
    {
      return responder()->success(Station::all(),StationTransformer::class)->respond();
    }

    public function findOne(int $id)
    {
        $station = Station::find($id);
        if($station){
            return responder()->success(Station::find($id),StationTransformer::class)->respond();
        }else{
            return $this->notfound();
        }
      
    }

    function notfound(){
        return response()->json([
                "status"=>200,
                "success"=>false,
                "message"=>"no records matches your request"
            ]);
    }
}

app/Http/Controllers/Admin/StationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Auth\Role\Role;
use App\Station;
use App\Panel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class StationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(auth()->user()->hasRole('admin')){
            return view('admin.stations.index', ['stations' => Station::paginate(10)]);
         } else{
             return redirect()->intended(route('admin.dashboard'));
         }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $station = new Station();
        return view('admin.stations.create',['station' => $station]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Station::create($request->all());
        return redirect()->intended(route('admin.stations'));
    }

    /**
     * Display the specified resource.
     *
     * @param Station $station
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Station $station)
    {
        return view('admin.stations.show', 
            [
                'station' => $station,
                'panels'  => Panel::where('station_id',$station->id)->paginate(10)
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Station $station
     * @return \Illuminate\Http\Response
     */
    public function edit(Station $station)
    {
        return view('admin.stations.edit', ['station' => $station]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Station $station
     * @return mixed
     */
    public function update(Request $request, Station $station)
    {
        $station->address = $request->address;
        $station->description = $request->description;
        $station->long = $request->long;
        $station->lat = $request->lat;
        $station->manager = $request->manager;
        $station->fax = $request->fax;
        $station->fix = $request->fix;
        $station->mobile = $request->mobile;
        $station->save();
        return redirect()->intended(route('admin.stations'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/stations/create.blade.php
@extends('admin.layouts.admin')

@section('title', 'Create New Station')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            {{ Form::open(['route'=>['admin.stations.store'],'method' => 'post','class'=>'form-horizontal form-label-left']) }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address" >
                        Address
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="address" type="text" class="form-control col-md-7 col-xs-12 "
                               name="address" value="{{ $station->address }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address" >
                        Description
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea name="description" id="description" cols="30" rows="10">{{ $station->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="log" >
                        Longitude
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="long" type="text" class="form-control col-md-7 col-xs-12 "
                               name="long" value="{{ $station->long }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="lat" >
                        Latitude
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="lat" type="text" class="form-control col-md-7 col-xs-12 "
                               name="lat" value="{{ $station->lat }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="manager" >
                        Manager
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="manager" type="text" class="form-control col-md-7 col-xs-12 "
                               name="manager" value="{{ $station->manager }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mobile" >
                        Mobile
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="mobile" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="mobile" value="{{ $station->mobile }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fix" >
                        Fix
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="fix" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="fix" value="{{ $station->fix }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fax" >
                        Fax
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="fax" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="fax" value="{{ $station->fax }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <a class="btn btn-primary" href="{{ URL::previous() }}"> {{ __('views.admin.users.edit.cancel') }}</a>
                        <button type="submit" class="btn btn-success"> {{ __('views.admin.users.edit.save') }}</button>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/users/edit.css')) }}
@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/users/edit.js')) }}
@endsection

resources/views/admin/stations/edit.blade.php
@extends('admin.layouts.admin')

@section('title',__('views.admin.users.edit.title', ['name' => $station->description]) )

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            {{ Form::open(['route'=>['admin.stations.update', $station->id],'method' => 'put','class'=>'form-horizontal form-label-left']) }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address" >
                        Address
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="address" type="text" class="form-control col-md-7 col-xs-12 "
                               name="address" value="{{ $station->address }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address" >
                        Description
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea name="description" id="description" cols="30" rows="10">{{ $station->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="log" >
                        Longitude
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="long" type="text" class="form-control col-md-7 col-xs-12 "
                               name="long" value="{{ $station->long }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="lat" >
                        Latitude
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="lat" type="text" class="form-control col-md-7 col-xs-12 "
                               name="lat" value="{{ $station->lat }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="manager" >
                        Manager
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="manager" type="text" class="form-control col-md-7 col-xs-12 "
                               name="manager" value="{{ $station->manager }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mobile" >
                        Mobile
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="mobile" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="mobile" value="{{ $station->mobile }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fix" >
                        Fix
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="fix" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="fix" value="{{ $station->fix }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fax" >
                        Fax
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="fax" type="tel" class="form-control col-md-7 col-xs-12 "
                               name="fax" value="{{ $station->fax }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <a class="btn btn-primary" href="{{ URL::previous() }}"> {{ __('views.admin.users.edit.cancel') }}</a>
                        <button type="submit" class="btn btn-success"> {{ __('views.admin.users.edit.save') }}</button>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/users/edit.css')) }}
@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/users/edit.js')) }}
@endsection

resources/views/admin/stations/index.blade.php
@extends('admin.layouts.admin')

@section('title','Stations')

@section('content')
    <div class="row">
        <a href="{{ route('admin.stations.create') }}" class="btn btn-primary pull-right" >Create a new Station</a>
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Description</th>
                <th>Panels</th>
                <th>Created At</th>
                <th>Updated At</th>

                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($stations as $station)
                <tr>
                    <td>{{ $station->id }}</td>
                    <td>{{ $station->address }}</td>
                    <td>{{ $station->description }}</td>
                    <td>{{ count($station->panels) }} <small>panels</small></td>
                    <td>{{ $station->created_at }}</td>
                    <td>{{ $station->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.stations.show', [$station->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.show') }}">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-info" href="{{ route('admin.stations.edit', [$station->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.edit') }}">
                            <i class="fa fa-pencil"></i>
                        </a>
                        {{--@if(!$user->hasRole('admin'))--}}
                            {{--<button class="btn btn-xs btn-danger user_destroy"--}}
                                    {{--data-url="{{ route('admin.stations.destroy', [$station->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">--}}
                                {{--<i class="fa fa-trash"></i>--}}
                            {{--</button>--}}
                        {{--@endif--}}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        
        <div class="row">
            <div class="col-md-12 text-center">{{ $stations->links() }}</div>
        </div>
    </div>
@endsection

resources/views/admin/stations/show.blade.php
@extends('admin.layouts.admin')

@section('title', 'Station', ['name' => $station->description]))

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>

            <tr>
                <th>Description</th>
                <td>{{ $station->description }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ $station->address }}</td>
            </tr>

            <tr>
                <th>Long</th>
                <td>{{ $station->long }}</td>
            </tr>
            <tr>
                <th>Lat</th>
                <td>{{ $station->lat }} </td>
            </tr>
            <tr>
                <th>Panels</th>
                <td>{{ count($station->panels) }} </td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ $station->created_at }} ({{ $station->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_7') }}</th>
                <td>{{ $station->updated_at }} ({{ $station->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
        <hr>
    </div>

    <div class="row">
        <h3>Children panels :</h3>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($panels as $panel)
                    <tr>
                        <td>{{ $panel->id }}</td>
                        <td>{{ $panel->name }}</td>
                        <td>{{ $panel->description }}</td>
                        <td>{{ $panel->created_at }}</td>
                        <td>{{ $panel->updated_at }}</td>
                        <td>
                            <a class="btn btn-xs btn-primary" href="{{ route('admin.panels.show', [$panel->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.show') }}">
                                <i class="fa fa-eye"></i>
                            </a>
                            {{--@if(!$user->hasRole('admin'))--}}
                                {{--<button class="btn btn-xs btn-danger user_destroy"--}}
                                        {{--data-url="{{ route('admin.stations.destroy', [$station->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">--}}
                                    {{--<i class="fa fa-trash"></i>--}}
                                {{--</button>--}}
                            {{--@endif--}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-12 text-center">{{ $panels->links() }}</div>
        </div>
    </div>
@endsection