routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('/', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login-form');;
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...

    // if (config('auth.users.registration')) {
        //Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    // }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    
    // Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    // Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    //Managers
    Route::get('users/manager/create', 'UserController@createManager')->name('users.create');
    Route::post('users/manager/store', 'UserController@storeManager')->name('users.manager.store');
    
    //Stations
    Route::get('stations', 'StationController@index')->name('stations');
    Route::post('stations', 'StationController@store')->name('stations.store');
    Route::get('stations/new', 'StationController@create')->name('stations.create');
    Route::get('stations/{station}', 'StationController@show')->name('stations.show');
    Route::get('stations/{station}/edit', 'StationController@edit')->name('stations.edit');
    Route::put('stations/{station}', 'StationController@update')->name('stations.update');

    //Panels
    Route::get('panels', 'PanelController@index')->name('panels');
    Route::post('panels', 'PanelController@store')->name('panels.store');
    Route::get('panels/new', 'PanelController@create')->name('panels.create');
    Route::get('panels/{panel}', 'PanelController@show')->name('panels.show');
    Route::get('panels/{panel}/edit', 'PanelController@edit')->name('panels.edit');
    Route::put('panels/{panel}', 'PanelController@update')->name('panels.update');

    //Operations
    Route::get('operations', 'OperationController@index')->name('operations');
    Route::post('operations', 'OperationController@index')->name('operations.filter');
    Route::get('operations/bystation/{id}', 'OperationController@filterByStation')->name('operations.filter.bystation');
    Route::post('operations/bystation/{id}', 'OperationController@filterByStation')->name('operations.filter.bystation');
    // Route::get('operations/bystation', 'OperationController@filterByStation')->name('operations.filter.bys');
    Route::get('operations/{operation}', 'OperationController@show')->name('operations.show');
    // Route::post('operations/filter/by-station', 'OperationController@filter')->name('operations.filter');
    
    // Route::post('operations', 'OperationController@store')->name('operations.store');
    // Route::get('operations/new', 'OperationController@create')->name('operations.create');
    // Route::get('operations/{operation}/edit', 'OperationController@edit')->name('operations.edit');
    // Route::put('operations/{operation}', 'OperationController@update')->name('operations.update');
    
    //Permissions
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
    Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
    Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');
});


// Route::get('/', 'HomeController@index');

/**
 * Membership
 */

// Route::group(['as' => 'protection.'], function () {
//     Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
//     Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
//     Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
// });

app/Panel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Panel extends Model
{
    public $sortable = ['created_at','station_id'];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'panels';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description','station_id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * Get the Station that owns the Panel.
     */
    function station(){
        return $this->belongsTo('App\Station');
    }

    function operations(){
        return $this->hasMany('App\Operation');
    }
}

app/Http/Controllers/API/PanelController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Auth\Role\Role;
use App\Panel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Http\Resources\PanelResource;
use Flugg\Responder\Responder;
use App\Transformers\PanelTransformer;

class PanelController extends Controller
{
    public function index()
    {
        return responder()->success(Panel::all(),new PanelTransformer())->respond();
    }

    
    public function findOne(int $id)
    {
        $panel = Panel::find($id);
        if(count($panel) >0){
            return responder()->success($panel,PanelTransformer::class)->respond();
        }else{
            return $this->notfound();
        }
      
    }
    public function findByStationId(int $id)
    {
        $panels = Panel::where('station_id',$id)->get();
        if(count($panels)>0){
            return responder()->success($panels,PanelTransformer::class)->respond();
        }else{
            return $this->notfound();
        }
      
    }

    protected function notfound(){
        return response()->json([
                "status"=>200,
                "success"=>false,
                "message"=>"no records matches your request"
            ]);
    }

}

app/Http/Controllers/Admin/PanelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Auth\Role\Role;
use App\Station;
use App\Panel;
use App\Operation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class PanelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(auth()->user()->hasRole('admin')){
            return view('admin.panels.index', [
                'panels' => Panel::paginate(10)
                ]
            );
         } else{
             return redirect()->intended(route('admin.dashboard'));
         }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $panel = new Panel();
        $stations = Station::all();
        return view('admin.panels.create',['panel' => $panel,'stations' => $stations]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Panel::create($request->all());
        return redirect()->intended(route('admin.panels'));
    }

    /**
     * Display the specified resource.
     *
     * @param Panel $panel
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Panel $panel)
    {
        return view('admin.panels.show', 
            [
                'panel' => $panel,
                'operations'=> Operation::where('panel_id',$panel->id)->paginate(10)
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Panel $panel
     * @return \Illuminate\Http\Response
     */
    public function edit(Panel $panel)
    {

        $stations = Station::all();
        return view('admin.panels.edit', ['panel' => $panel,'stations' => $stations]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Panel $panel
     * @return mixed
     */
    public function update(Request $request, Panel $panel)
    {
        $panel->name = $request->name;
        $panel->description = $request->description;
        $station = Station::find($request->station_id);
        $panel->station_id = $station->id;
        $panel->save();
        return redirect()->intended(route('admin.panels'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/panels/create.blade.php
@extends('admin.layouts.admin')

@section('title', 'Create New Panel')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
             {{ Form::open(['route'=>['admin.panels.store'],'method' => 'post','class'=>'form-horizontal form-label-left']) }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name" >
                        Name
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="name" type="text" class="form-control col-md-7 col-xs-12 "
                               name="name" value="{{ $panel->name }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description" >
                        Description
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea name="description" id="description" cols="30" rows="10">{{ $panel->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="station_id" >
                        Station
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select name="station_id" id="station_id" class="form-control col-md-7 col-xs-12 ">
                        @foreach($stations as $station)
                        <option value="{{$station->id}}">{{$station->description}}</option>
                        @endforeach
                        </select>
                        
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <a class="btn btn-primary" href="{{ URL::previous() }}"> {{ __('views.admin.users.edit.cancel') }}</a>
                        <button type="submit" class="btn btn-success"> {{ __('views.admin.users.edit.save') }}</button>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/users/edit.css')) }}
@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/users/edit.js')) }}
@endsection

resources/views/admin/panels/edit.blade.php
@extends('admin.layouts.admin')

@section('title','Panel', ['name' => $panel->name]) )

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            {{ Form::open(['route'=>['admin.panels.update', $panel->id],'method' => 'put','class'=>'form-horizontal form-label-left']) }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name" >
                        Name
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="name" type="text" class="form-control col-md-7 col-xs-12 "
                               name="name" value="{{ $panel->name }}" required>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description" >
                        Description
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <textarea name="description" id="description" cols="30" rows="10">{{ $panel->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="station_id" >
                        Station
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select name="station_id" id="station_id" class="form-control col-md-7 col-xs-12 ">
                        @foreach($stations as $station)
                        <option value="{{$station->id}}">{{$station->description}}</option>
                        @endforeach
                        </select>
                        
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <a class="btn btn-primary" href="{{ URL::previous() }}"> {{ __('views.admin.users.edit.cancel') }}</a>
                        <button type="submit" class="btn btn-success"> {{ __('views.admin.users.edit.save') }}</button>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/users/edit.css')) }}
@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/users/edit.js')) }}
@endsection

resources/views/admin/panels/index.blade.php
@extends('admin.layouts.admin')

@section('title','Panels')

@section('content')
    <div class="row">
        <a href="{{ route('admin.panels.create') }}" class="btn btn-primary pull-right" >Create a new panel </a>
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Parent Station</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($panels as $panel)
                <tr>
                    <td>{{ $panel->id }}</td>
                    <td>{{ $panel->name }}</td>
                    <td>{{ $panel->description }}</td>
                    <td>{{ $panel->created_at }}</td>
                    <td>{{ $panel->updated_at }}</td>
                    <td>{{ $panel->station->description }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.panels.show', [$panel->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.show') }}">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-info" href="{{ route('admin.panels.edit', [$panel->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.edit') }}">
                            <i class="fa fa-pencil"></i>
                        </a>
                        {{--@if(!$user->hasRole('admin'))--}}
                            {{--<button class="btn btn-xs btn-danger user_destroy"--}}
                                    {{--data-url="{{ route('admin.stations.destroy', [$station->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">--}}
                                {{--<i class="fa fa-trash"></i>--}}
                            {{--</button>--}}
                        {{--@endif--}}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-12 text-center">{{ $panels->links() }}</div>
        </div>
        
    </div>
@endsection

resources/views/admin/panels/show.blade.php
@extends('admin.layouts.admin')

@section('title', 'Panel', ['name' => $panel->description]))

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>

            <tr>
                <th>Description</th>
                <td>{{ $panel->name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ $panel->description }}</td>
            </tr>

            <tr>
                <th>Parent Station</th>
                <td>{{ $panel->station->description }} </td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ $panel->created_at }} ({{ $panel->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_7') }}</th>
                <td>{{ $panel->updated_at }} ({{ $panel->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
    </div>
    <hr>

    <div class="row">
        @if(count($operations)>0)
        <h3>Children operations :</h3>
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>Agent</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($operations as $operation)
                <tr>
                    <td>{{ $operation->id }}</td>
                    <td>{{ $operation->agent->name }}</td>
                    <td>{{ $operation->created_at }}</td>
                    <td>{{ $operation->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.operations.show', [$operation->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.show') }}">
                            <i class="fa fa-eye"></i>
                        </a>
                        {{--@if(!$user->hasRole('admin'))--}}
                            {{--<button class="btn btn-xs btn-danger user_destroy"--}}
                                    {{--data-url="{{ route('admin.stations.destroy', [$operation->id]) }}" data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">--}}
                                {{--<i class="fa fa-trash"></i>--}}
                            {{--</button>--}}
                        {{--@endif--}}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="row">
            <div class="col-md-12 text-center">{{ $operations->links() }}</div>
        </div>
        @endif

        @if(count($operations)==0)
        <h3>No operations yet !</h3>
        @endif
    </div>

@endsection